spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/luxuryvoice?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    diver-class-name: com.mysql.jdbc.Driver