spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/schoolnet?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    diver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  mapper-locations: classpath*:mybatis/**/Mysql_*Mapper.xml

server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8120
    context-path: /